### ISSUE TITLE
Inputs must be at least 4-band rasters when using the option `--split`

### ISSUE THREAD

**Issue by pqiaohaoq** [OpenDroneMap/ODM#1129]
https://github.com/OpenDroneMap/ODM/blob/b698a087a046148c83f15945b0f54b09f807132e/opendm/orthophoto.py#L168-L169

Why do it need to check the count here?

when the image itself is only 1-band raster, the option `--split` specified won't work properly!

**Comment by pierotofy** [comment]
Mostly because we wrote split-merge before we supported single-band and multispectral inputs, and we added some assertions checks for RGB(A) datasets only. The whole split-merge pipeline needs to be checked/tested against these, and possibly modified in places like the one you found.

Interested in helping us with this?

**Comment by pqiaohaoq** [comment]
Yes, I will try.
