### ISSUE TITLE
baseimage phusion/baseimage:latest

### ISSUE THREAD

**Issue by abarghou1993** [OpenDroneMap/ODM#1148]
### How did you install OpenDroneMap? (Docker, natively, ...)?

[Docker]

### What's your browser and operating system? (Copy/paste the output of https://www.whatismybrowser.com/)

[Ubuntu 18.04 ]

### What is the problem?

Step 1/30 : FROM phusion/baseimage
manifest for phusion/baseimage:latest not found: manifest unknown: manifest unknown

### What should be the expected behavior? If this is a feature request, please describe in detail the changes you think should be made to the code, citing files and lines where changes should be made, if possible.

[the phusion/baseimage with latest tag cannot be pulled any longer]

### How can we reproduce this? (What steps did you do to trigger the problem? What parameters are you using for processing? If possible please include a copy of your dataset uploaded on Google Drive or Dropbox. Be detailed)

[docker pull phusion/baseimage]

**Comment by tiagodc** [comment]
It seems to be an error with the [phusion docker repo](https://hub.docker.com/r/phusion/baseimage/).

I tried building phusion with the latest tag explicitly (`phusion/baseimage:master-amd64`) and got the following error:

```
Err:7 http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu focal Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists...
E: The repository 'http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu focal Release' does not have a Release file.
The command '/bin/sh -c add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable   && add-apt-repository -y ppa:george-edison55/cmake-3.x   && apt-get update -y   && apt-get install --no-install-recommends -y   build-essential   cmake   gdal-bin   git   libatlas-base-dev   libavcodec-dev   libavformat-dev   libboost-date-time-dev   libboost-filesystem-dev   libboost-iostreams-dev   libboost-log-dev   libboost-python-dev   libboost-regex-dev   libboost-thread-dev   libeigen3-dev   libflann-dev   libgdal-dev   libgeotiff-dev   libgoogle-glog-dev   libgtk2.0-dev   libjasper-dev   libjpeg-dev   libjsoncpp-dev   liblapack-dev   liblas-bin   libpng-dev   libproj-dev   libsuitesparse-dev   libswscale-dev   libtbb2   libtbb-dev   libtiff-dev   libvtk6-dev   libxext-dev   python-dev   python-gdal   python-matplotlib   python-pip   python-software-properties   python-wheel   software-properties-common   swig2.0   grass-core   libssl-dev   && apt-get remove libdc1394-22-dev   && pip install --upgrade pip   && pip install setuptools' returned a non-zero code: 100
```

*edit: My setup runs Ubuntu 18.04 on a Dell XPS 9350 

*edit 2: error when trying to build with tag `18.04-1.0.0`:

```
Err:7 http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu bionic Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists...
E: The repository 'http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu bionic Release' does not have a Release file.
The command '/bin/sh -c add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable   && add-apt-repository -y ppa:george-edison55/cmake-3.x   && apt-get update -y   && apt-get install --no-install-recommends -y   build-essential   cmake   gdal-bin   git   libatlas-base-dev   libavcodec-dev   libavformat-dev   libboost-date-time-dev   libboost-filesystem-dev   libboost-iostreams-dev   libboost-log-dev   libboost-python-dev   libboost-regex-dev   libboost-thread-dev   libeigen3-dev   libflann-dev   libgdal-dev   libgeotiff-dev   libgoogle-glog-dev   libgtk2.0-dev   libjasper-dev   libjpeg-dev   libjsoncpp-dev   liblapack-dev   liblas-bin   libpng-dev   libproj-dev   libsuitesparse-dev   libswscale-dev   libtbb2   libtbb-dev   libtiff-dev   libvtk6-dev   libxext-dev   python-dev   python-gdal   python-matplotlib   python-pip   python-software-properties   python-wheel   software-properties-common   swig2.0   grass-core   libssl-dev   && apt-get remove libdc1394-22-dev   && pip install --upgrade pip   && pip install setuptools' returned a non-zero code: 100
```

**Comment by pierotofy** [comment]
Mm, that seems to be the case. We should probably switch `Dockerfile` and `portable.Dockerfile` to use `ubuntu:16.04` instead.

Would you be interested in opening a pull request?

**Comment by tiagodc** [comment]
Investigating the issue a bit further I saw that the `latest` tag is not really the "latest" release. The latest `phusion/baseimage` release does not use ubuntu 16.04 for more than a year already. On top of that, the `http://ppa.launchpad.net/george-edison55/cmake-3.x/` is deprecated since ubuntu 18.04. The packages that depend on that ppa are:

```
E: Unable to locate package libjasper-dev
E: Package 'python-software-properties' has no installation candidate
E: Package 'swig2.0' has no installation candidate
```

There are a couple possible fixes here: (1) use an older phusion/baseimage reference (e.g. v0.10.2) that runs ubuntu 16.04, or (2) update the Dockerfile with the new lib sources to run under ubuntu 18.04.

I can open a pull request, sure. Which fix would you recommend?
- (1) is a quick fix
- (2) will update the image to a more "state of the art" technology but might have some side effects or dependency issues that will need further validation and testing after building

**Comment by pierotofy** [comment]
Oh, interesting... I wonder why we haven't been receiving more reports about building issues (I'm fairly certain some things would not work properly on newer Ubuntu versions, but maybe they do).

We have medium term plans to migrate the ODM codebase to Python 3 as well as upgrading to Ubuntu 20.04.

For the time being, I found the original phusion image we've been using (from 2 years ago) and pushed it to `opendronemap/phusion-baseimage`. We can probably just change it to that for now, since we'll switch to a newer image in the medium term.

**Comment by tiagodc** [comment]
Alright. I'm building it right now using `phusion/baseimage:0.10.2` and it is going smoothly so far. Should I still open the pull request?

**Comment by pierotofy** [comment]
To err on the safe side I would use `opendronemap/phusion-baseimage`, but yes feel free to open a PR!
