### ISSUE TITLE
OpenSfM Kmeans error running --split 4 on the banana dataset.

### ISSUE THREAD

**Issue by jchen706** [OpenDroneMap/ODM#1153]
![image](https://user-images.githubusercontent.com/32785168/91117261-2c219700-e65c-11ea-98f3-25b15db5f70d.png)

![image](https://user-images.githubusercontent.com/32785168/91117271-3479d200-e65c-11ea-9d0c-19fecdf8d5b3.png)

The command I ran was : 
![image](https://user-images.githubusercontent.com/32785168/91117310-4e1b1980-e65c-11ea-9dbe-7fbe6f564cad.png)

I install with docker image.

I think it's a GPS error, I didn't have GPS and need a image_group.txt. Do you know where to put the image_group.txt in the folder structure of /project/images
images folder is the images.

Also which of the datasets in OpenDroneMap sample datasets have GPS coordinates?

**Comment by smathermather** [comment]
https://community.opendronemap.org is a better place to ask questions, but that said, as you discerned you'll get an error with a split size of 4 because split merge does make an assumption that it is geographic data. Also, a split size that small is unlikely to work. I wouldn't recommend going smaller than 16 or 32 as your smallest size, and would recommend going as large as your hardware allows.
