### ISSUE TITLE
WebODM: a web interface for OpenDroneMap

### ISSUE THREAD

**Issue by dakotabenjamin** [OpenDroneMap/ODM#137]
Hi all,

I began working on a web interface for ODM in Flask (in anticipation for the python port). You can find it [here](https://github.com/dakotabenjamin/WebODM). It is currently in heavy development mode, so there's nothing really there except a login/registration form. I thought it would be prudent to inform the community of this project as it develops over the next few weeks, and of course any feedback would be welcome.

**Comment by dbrgn** [comment]
Hi @dakotabenjamin. I just added a PR with a Dockerfile: https://github.com/OpenDroneMap/OpenDroneMap/pull/143

Maybe it would make sense if the web interface would launch a Docker container to process the data, instead of running the operations locally? That would also allow you to process multiple image sets at the same time, or launching a processing job on a remote server.
