### ISSUE TITLE
Possible Bug: Rolling Shutter Distortion Correction applied only to primary band image 

### ISSUE THREAD

**Issue by Saijin-Naib** [OpenDroneMap/ODM#1479]
As per ckato3 here: 
https://community.opendronemap.org/t/important-feature-update-rolling-shutter-distortion-correction/12032/3?u=saijin_naib

It seems like only the primary band image from a set of mult-band images (one image per channel) gets corrected, leading to compounded misalignment between bands in the dataset.

**Comment by pierotofy** [comment]
I'm not sure this is really a bug; we don't perform correction on the image pixels, just on the feature extraction process, so the warp matrix calculation should not be affected at all.

A dataset to test issues with multispectral issues and rolling shutter (with before and after screenshots) would be nice to validate any issues.

**Comment by Saijin-Naib** [comment]
Sounds good. I'll follow up with the reporter and ask them to give test data and results here.

**Comment by ckato3** [comment]
Stripe-like borders appear on the NDVI image from a grid pattern flight with multiple turns to the north and south.
This phenomenon does not appear in subsets of images taken only northward or only southward.
So I suppose this come from that inter-band warp matrices are different for northward or southward due to rolling shutter distortion.

This boundary is barely noticeable in the red and near-infrared images.
It is noticeable only  calculated NDVI images.

Also, this phenomenon is not seen with Sequoia cameras using GLOBAL shutter multi-band cameras.
It is noticeable on the DJI P4 Multispectral which I believe use ROLLING shutter cameras.

I will upload sample images, probably NEXT week.

**Comment by pierotofy** [comment]
But is this an issue related to turning on `--rolling-shutter`? In other words, you don't get the artifacts if you don't specify `--rolling-shutter`?

**Comment by ckato3** [comment]
I'm a bit confused.

Looking at the ODM log file, if the --rolling-shutter option is enabled, I see
     [INFO]   running "/code/SuperBuild/   ...   /opensfm"   rs_correct   "/code/opensfm"
     ......
     INFO: Correcting observations...
     INFO: Writing corrected and trimmed features for DJI_0873.TIFF

It reads as if an image file with rolling shutter correction is being written out at this opensfm stage.

If that is true, then changing "rs_correct" to apply the correction to all band images, 
Then, at the later stage, the band alignment will be performed using the rolling shutter corrected images, and the warp matrix will be obtained.
(The band alignment can be obtained without the effects of rolling shutter distortion.)

Or, is the image file itself unaltered at "opensfm rs_correcrt" stage, and does not affect subsequent calculations ?

**Comment by pierotofy** [comment]
> It reads as if an image file with rolling shutter correction is being written out at this opensfm stage.

It writes *features*, not *images*.

>  is the image file itself unaltered

Correct! 

Feel free to re-open if you have a dataset you can share showing issues with `--rolling-shutter`.
