### ISSUE TITLE
Add support for P4 camera+sun calibration

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#1483]
Currently the Phantom 4 multispectral sun sensor calibration does not work properly. Some modifications to the code need to be implemented to support it.

Reference: https://dl.djicdn.com/downloads/p4-multispectral/20200717/P4_Multispectral_Image_Processing_Guide_EN.pdf

Community thread: https://community.opendronemap.org/t/dji-p4m-segmented-orthophoto/12039/15

**Comment by Christoffer-Svenningsson** [comment]
I was curious whether ODM actually was reading all the meta-data from images coming from P4 correctly and noticed that there are several members in a loaded ODM_photo instance set to None or 0 which probably should not be. I am trying to add XMP-tags where i see fit in ODM_photo but I am very new to working with this kind of data and I struggle to translate what everything is. 

For instance: 
Is DLS (yaw pitch roll) same as Irrradiance (yaw pitch roll)?
Is DarkLevel same as BlackLevel?
What is horizontal irradiance and how does it compare to irradiance?

I am searching for information but if anyone has input it would be helpful!

Update: Just so no one else falls in this pitfall. The "Camera:RadiometricCalibration" tag in P4 should probably not be used and cant be compared to the radiometric calibration of micasense cameras, just ignore it. The first element is just a copy of "@drone-dji:SensorGainAdjustment" and can thus be greater than 1 which makes no sense at all for a radiometric calibration value.

Update2: My modifications to the code seems to be calculating indices such as NDVI correctly now. But i cant get the individual bands correct. I believe this is because I dont understand how to calculate rho_X as mentioned in the [DJI P4 Multispectral Image processing guide ](https://dl.djicdn.com/downloads/p4-multispectral/20200717/P4_Multispectral_Image_Processing_Guide_EN.pdf). Please tell me if anyone has an idea of how to calculate this.

**Comment by pierotofy** [comment]
I don't think you actually need to compute $\rho_x$ directly, to my understanding the white paper boils down to implementing:

![image](https://user-images.githubusercontent.com/1951843/181313010-95e3966a-3e53-4228-a889-67b206b4a6ba.png)

`XCamera = dn_to_radiance code`
`pCam_X  = sensor gain adjustment from XMP`
`XLS * pLS_X = spectral_irradiance` (MicaSense calls this horizontal irradiance, also read from XMP)

I've added some changes with #1513 and I'm running some tests to see if the results look plausible.

**Comment by pierotofy** [comment]
And yes I don't think we want to use `Camera:RadiometricCalibration`.

**Comment by Christoffer-Svenningsson** [comment]
> I don't think you actually need to compute ρx directly, to my understanding the white paper boils down to implementing:
> 
> ![image](https://user-images.githubusercontent.com/1951843/181313010-95e3966a-3e53-4228-a889-67b206b4a6ba.png)
> 
> `XCamera = dn_to_radiance code` `pCam_X = sensor gain adjustment from XMP` `XLS * pLS_X = spectral_irradiance` (MicaSense calls this horizontal irradiance, also read from XMP)

Yes this is what i tried to do aswell. (My code was horrible which is why i did not share it by the way). This makes the normalized indices such as NDVI look ok. But the individual bands still seems off. Maybe I am missing something here? Or do we simply ignore the individual bands and only do this to use with indices?

**Comment by pierotofy** [comment]
Can you post some screenshots?

I would also recommend to test #1513 and see how it compares to what you wrote.

**Comment by Christoffer-Svenningsson** [comment]
I will attempt to connect to the computer in which I have the images and get them. Give me a few minutes!

**Comment by pierotofy** [comment]
I also think the polynomial coefficients for vignetting for the Phantom 4 are stored inverted compared to other sensors like the Micasense.

**Comment by Christoffer-Svenningsson** [comment]
This is what  qgis "default" min/max colorthreshhold gives. Note that there does not seem to be a common ceil for the values? How can i even determine this when representing the image
![Selection_005](https://user-images.githubusercontent.com/71757262/181348539-d8382a41-01d1-47a4-a4fa-f6d64e8d1fda.png)

This is what i get if i set the same colortreshhold.
![Selection_006](https://user-images.githubusercontent.com/71757262/181348530-38412595-4bdf-439f-a9c9-3f9c2b2c67e6.png)

This is with global seam leveling on.
![Selection_007](https://user-images.githubusercontent.com/71757262/181348536-6d9ef79b-5d27-4ea2-b73d-d4cc132d5033.png)

It should be mentioned that this was a sunny day and pretty much all colors should be similar to the lighter patch (more or less) as seen in the second image

Also, I will test #1513 tomorrow for sure. This is quite exciting, glad you are taking your time to add support for this messy drone!

**Comment by Christoffer-Svenningsson** [comment]
> I also think the polynomial coefficients for vignetting for the Phantom 4 are stored inverted compared to other sensors like the Micasense.

Yes, from my understanding we do not multiply by 1/V(x,y) but instead just V(x,y). I changed this aswell. If I understood you correctly.

**Comment by pierotofy** [comment]
Correct.

I'm getting decent results with #1513

![image](https://user-images.githubusercontent.com/1951843/181358718-a8aee549-026c-4668-8de6-2c7f38ad7368.png)

![image](https://user-images.githubusercontent.com/1951843/181359000-e0f97c37-5b40-4fb8-bb96-1d9115926bed.png)

I think I'll go ahead and merge it, that way more people can start testing it out. We can fix other issues as they come out.

**Comment by Christoffer-Svenningsson** [comment]
> Correct.
> 
> I'm getting decent results with #1513
> 
> 
> I think I'll go ahead and merge it, that way more people can start testing it out. We can fix other issues as they come out.

This was a better example of the miscoloring for the RGB bands i was talking about, sorry i could not find a better example. Anyways, great job and thank you for fixing this again!

**Comment by Christoffer-Svenningsson** [comment]
This is what i got with #1513. It's looking kind of strange. 
![Selection_008](https://user-images.githubusercontent.com/71757262/181464098-b854aa87-d812-45ca-96e8-addc6caa1e00.png)

NDVI in grey scale
![Selection_009](https://user-images.githubusercontent.com/71757262/181464586-42a83ac3-ce8a-410b-96ef-830155f3b002.png)

I dont know. Maybe this dataset is just bad for some reason

**Comment by pierotofy** [comment]
Maybe. Can you share the images?

**Comment by Christoffer-Svenningsson** [comment]
> Maybe. Can you share the images?

You mean the raw data right? Im just waiting for an OK to share it just to be certain

**Comment by Christoffer-Svenningsson** [comment]
Hi, here is the dataset. It's my first time using dronedb. I hope i made it public so that you can view it!
The flight was automatic and with 75% side overlap and 80% front overlap.
[DroneDB P4M Test dataset](https://hub.dronedb.app/r/ffop/p4m-75_overlap-testdata)

**Comment by pierotofy** [comment]
There's definitely some value intensity issue going on with this dataset, but I'm not sure if this is something that we're not correcting properly in ODM, or if the sensor just wasn't calibrated properly prior to data capture, or something else.

I've checked the code and we're doing everything that DJI documented to do, so I'm not sure.

**Comment by pierotofy** [comment]
One thing I made sure to check is that mvs-texturing is not causing the artifacts, I manually overlaid the RGB images after radiometric-calibration and this is what came out of it:

![image](https://user-images.githubusercontent.com/1951843/181658603-69c71c20-7fb0-4d6e-9646-2154be350cf2.png)

It just doesn't look correct, but I'm not sure how to adjust it (especially given that other datasets seem to work).

Another image from the dataset instead looks more correct:

![image](https://user-images.githubusercontent.com/1951843/181659110-1c91d29e-347d-4839-a539-7aae9bc24e46.png)

So perhaps some images are good and others are not, explaining the strange intensity patterns in the final orthophoto. But feel free to poke around, perhaps I've missed something.

**Comment by pierotofy** [comment]
In particular, both sensor gain and exposure time between the good/bad shots are widely different:

```
DJI_0771.TIF
drone-dji:SensorGain="3.750"
drone-dji:ExposureTime="3040"

DJI_0311.TIF
drone-dji:SensorGain="1.000"
drone-dji:ExposureTime="283"
```

I'm not sure why that is, but it's probably the cause.

**Comment by Christoffer-Svenningsson** [comment]
> In particular, both sensor gain and exposure time between the good/bad shots are widely different:
> 
> ```
> DJI_0771.TIF
> drone-dji:SensorGain="3.750"
> drone-dji:ExposureTime="3040"
> 
> DJI_0311.TIF
> drone-dji:SensorGain="1.000"
> drone-dji:ExposureTime="283"
> ```
> 
> I'm not sure why that is, but it's probably the cause.

So the testdata i have been testing my changes to has been bad... Thats painful to hear. I wonder if the drone is broken. Thank you for this investigation anyway. Right now im out of ideas on what to investigate. But I will write here if anything comes up!

Edit: Maybe the fact that we are missing the rho_nir factor is playing a role here?
Edit2: I found an old discussion about this issue on the DJI forums. It seems like im not the only one having this issue https://forum.dji.com/thread-231375-1-1.html. Feels like a relief to know that the drone might not be broken atleast

**Comment by EvaGith** [comment]
Thanks for the very interesting thread. I need some guidance about how to use the orthomosaic output to derive NDVI and other spectral indices. The output is float32 reflectance values, but since they are not in the 0-1 values range, how should I proceed? Does the orthomosaic need some normalization or any other further processing? It's my first time processing drone imagery and I am trying to figure out a suitable processing pipeline. Thanks again!

**Comment by MendeBadra** [comment]
I don't get it. Is the camera+sun option supported for DJI Phantom 4 drones?

**Comment by EvaGith** [comment]
In Pix4D I can select those options...but not sure how to make it work in ODM

<img width="381" alt="Image" src="https://github.com/user-attachments/assets/e2f92079-e819-4b7f-abb6-abe0baa798f9" />

Specifications: 
The DJI Phantom 4 Multispectral drone has a sunlight sensor that helps to improve the consistency of data collection at different times of the day

**Comment by MendeBadra** [comment]
I am trying camera + sun for my dataset on ODM. Did you get Pix4D license by trial?

**Comment by EvaGith** [comment]
Are you able to obtain reflectance values in the output of the processing with camera+sun? I never did in ODM. I got the chance of contrasting my attempts in ODM with some colleagues at the university who had access to an educational Pix4D licence. Please let me know about your findings! I have been wondering how to solve it in ODM for almost a year now!

**Comment by MendeBadra** [comment]
I have finished processing. pc-quality: ultra was a bad idea, my pc memory filled. After that I got a patchy image but I believe it's due to `texturing-skip-global-seam-leveling` (I kinda read a lot of thread and mixed up which option contributes to which)

![Image](https://github.com/user-attachments/assets/5d920262-a1a3-4bc2-988f-10b0badf6ed6)

I will let you know about result without `texturing-skip-global-seam-leveling` tomorrow. (By the way one of my drone captures is producing this uneven lighting conditions no matter what (here is other image that I mosaicked)):

![Image](https://github.com/user-attachments/assets/ac5a1812-be63-4958-9733-dfc1a8a78e46)

**Comment by EvaGith** [comment]
I also managed mosaicking (different processing options, different outcomes). Visual inspection was ok. However, the histogram and the pixel value ranges were odd (not correct, histogram showed a weird distribution, and values were not in reflectances range (0-1) at all). :-( how about yours?

**Comment by MendeBadra** [comment]
My computer froze multiple times. I have queued another run. I'll let you know the results.

**Comment by MendeBadra** [comment]
I finished orthomosaicing and I don't know why in the middle, area of sudden bright spot appeared. Take a look: 

![Image](https://github.com/user-attachments/assets/fcffe6ae-8ae4-407e-bb60-9b249bae3099)

My parameters are:
auto-boundary:true, feature-quality:ultra, mesh-octree-depth:12, mesh-size:600000, optimize-disk-space:true, orthophoto-resolution:0.001, pc-quality:high, radiometric-calibration:camera+sun, rolling-shutter:true

**Comment by EvaGith** [comment]
Did you check the histograms? What are the range values? It's not only a matter of visual inspection. You should obtain values between 0-1 in the pixels and a proper values distribution. I never managed though...trying different processing options for the phantom 4 multiespectral didn't render reflectances ...weird histograms all the time 

Yahoo Mail: Busca, organiza, conquista 
 
  El vie, abr 18, 2025 a 5:04, Mend-Amar ***@***.***> escribió:    
I finished orthomosaicing and I don't know why in the middle, area of sudden bright spot appeared. Take a look:

image.png (view on web)

My parameters are:
auto-boundary:true, feature-quality:ultra, mesh-octree-depth:12, mesh-size:600000, optimize-disk-space:true, orthophoto-resolution:0.001, pc-quality:high, radiometric-calibration:camera+sun, rolling-shutter:true

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>
MendeBadra left a comment (OpenDroneMap/ODM#1483)
I finished orthomosaicing and I don't know why in the middle, area of sudden bright spot appeared. Take a look:

image.png (view on web)

My parameters are:
auto-boundary:true, feature-quality:ultra, mesh-octree-depth:12, mesh-size:600000, optimize-disk-space:true, orthophoto-resolution:0.001, pc-quality:high, radiometric-calibration:camera+sun, rolling-shutter:true

**Comment by MendeBadra** [comment]
Hello, there is the histogram values and some boxplots showing max and min: (I would say they're pretty normal looking histograms)

![Image](https://github.com/user-attachments/assets/e5bf336d-7621-4642-8a0c-070f7b9b518c)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Band</th>
      <th>Min</th>
      <th>Max</th>
      <th>Mean</th>
      <th>Median</th>
      <th>Std Dev</th>
      <th>Count</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Red (Band 1)</td>
      <td>0.000010</td>
      <td>0.801670</td>
      <td>0.111174</td>
      <td>0.104933</td>
      <td>0.038385</td>
      <td>72930440</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Green (Band 2)</td>
      <td>0.000037</td>
      <td>0.657114</td>
      <td>0.103182</td>
      <td>0.098467</td>
      <td>0.032011</td>
      <td>72931495</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Blue (Band 3)</td>
      <td>0.000153</td>
      <td>0.551923</td>
      <td>0.104978</td>
      <td>0.099838</td>
      <td>0.031800</td>
      <td>72931862</td>
    </tr>
    <tr>
      <th>3</th>
      <td>NIR (Band 4)</td>
      <td>0.000064</td>
      <td>0.819185</td>
      <td>0.197075</td>
      <td>0.187860</td>
      <td>0.060731</td>
      <td>72931525</td>
    </tr>
    <tr>
      <th>4</th>
      <td>RedEdge (Band 5)</td>
      <td>0.000005</td>
      <td>0.724430</td>
      <td>0.141161</td>
      <td>0.134643</td>
      <td>0.045160</td>
      <td>72930929</td>
    </tr>
    <tr>
      <th>5</th>
      <td>Band 6 (Band 6)</td>
      <td>255.000000</td>
      <td>255.000000</td>
      <td>255.000000</td>
      <td>255.000000</td>
      <td>0.000000</td>
      <td>72931873</td>
    </tr>
  </tbody>
</table>
</div>

![Image](https://github.com/user-attachments/assets/96951fad-e299-41b9-b480-abdfd7a83777)

**Comment by EvaGith** [comment]
Yes, it looks fine indeed...however visually there are brightness heterogeneities. I am not sure how to correct for those...I'll give it a try using your processing parameters over one of my flights (also covering a shrubland area) to compare with the ones you are applying. I didn't even get reflectance values (and my histograms are shameful!). I thought the issue was some ODM developments incompatibility with the Phantom4MS, but you did manage (at least numerically...)
Maybe other users can shed some light into this? 
I'll be back when I manage to process the flight.
thanks for sharing! Cheers,
Eva
Yahoo Mail: Busca, organiza, conquista 
 
  El dom, abr 20, 2025 a 6:34, Mend-Amar ***@***.***> escribió:    
Hello, there is the histogram values and some boxplots showing max and min: (I would say they're pretty normal looking histograms)

image.png (view on web)
<style scoped> .dataframe tbody tr th:only-of-type { vertical-align: middle; }.dataframe tbody tr th {
    vertical-align: top;
}

.dataframe thead th {
    text-align: right;
}
</style>
|  | Band | Min | Max | Mean | Median | Std Dev | Count |
| 0 | Red (Band 1) | 0.000010 | 0.801670 | 0.111174 | 0.104933 | 0.038385 | 72930440 |
| 1 | Green (Band 2) | 0.000037 | 0.657114 | 0.103182 | 0.098467 | 0.032011 | 72931495 |
| 2 | Blue (Band 3) | 0.000153 | 0.551923 | 0.104978 | 0.099838 | 0.031800 | 72931862 |
| 3 | NIR (Band 4) | 0.000064 | 0.819185 | 0.197075 | 0.187860 | 0.060731 | 72931525 |
| 4 | RedEdge (Band 5) | 0.000005 | 0.724430 | 0.141161 | 0.134643 | 0.045160 | 72930929 |
| 5 | Band 6 (Band 6) | 255.000000 | 255.000000 | 255.000000 | 255.000000 | 0.000000 | 72931873 |

 
image.png (view on web)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>
MendeBadra left a comment (OpenDroneMap/ODM#1483)
Hello, there is the histogram values and some boxplots showing max and min: (I would say they're pretty normal looking histograms)

image.png (view on web)
<style scoped> .dataframe tbody tr th:only-of-type { vertical-align: middle; }.dataframe tbody tr th {
    vertical-align: top;
}

.dataframe thead th {
    text-align: right;
}
</style>
|  | Band | Min | Max | Mean | Median | Std Dev | Count |
| 0 | Red (Band 1) | 0.000010 | 0.801670 | 0.111174 | 0.104933 | 0.038385 | 72930440 |
| 1 | Green (Band 2) | 0.000037 | 0.657114 | 0.103182 | 0.098467 | 0.032011 | 72931495 |
| 2 | Blue (Band 3) | 0.000153 | 0.551923 | 0.104978 | 0.099838 | 0.031800 | 72931862 |
| 3 | NIR (Band 4) | 0.000064 | 0.819185 | 0.197075 | 0.187860 | 0.060731 | 72931525 |
| 4 | RedEdge (Band 5) | 0.000005 | 0.724430 | 0.141161 | 0.134643 | 0.045160 | 72930929 |
| 5 | Band 6 (Band 6) | 255.000000 | 255.000000 | 255.000000 | 255.000000 | 0.000000 | 72931873 |

 
image.png (view on web)

**Comment by EvaGith** [comment]
I don't know what to say: after trying different processing options, I am not sure what's best. The reflectances values change for each one and I am not certain how to decide which is best. One of the combinations I used is: --auto-boundary--feature-quality ultra--optimize-disk-space--orthophoto-resolution 5--dem-resolution 1 --min-num-features 24000 --radiometric-calibration camera+sun--texturing-skip-global-seam-leveling --orthophoto-no-tiled --orthophoto-compression DEFLATE--use-exif--pc-quality high--texturing-data-term--mesh-octree-depth 12--mesh-size 600000
I see that using the command line in ODM instead of WebODM might help computationally?
About the artifacts, does anybody know how to smooth them somehow? 

 

 

    En lunes, 21 de abril de 2025, 11:00:49 CEST, Eva Sevillano ***@***.***> escribió:  
 
 Yes, it looks fine indeed...however visually there are brightness heterogeneities. I am not sure how to correct for those...I'll give it a try using your processing parameters over one of my flights (also covering a shrubland area) to compare with the ones you are applying. I didn't even get reflectance values (and my histograms are shameful!). I thought the issue was some ODM developments incompatibility with the Phantom4MS, but you did manage (at least numerically...)
Maybe other users can shed some light into this? 
I'll be back when I manage to process the flight.
thanks for sharing! Cheers,
Eva
Yahoo Mail: Busca, organiza, conquista 
 
  El dom, abr 20, 2025 a 6:34, Mend-Amar ***@***.***> escribió:    
Hello, there is the histogram values and some boxplots showing max and min: (I would say they're pretty normal looking histograms)

image.png (view on web)
<style scoped> .dataframe tbody tr th:only-of-type { vertical-align: middle; }.dataframe tbody tr th {
    vertical-align: top;
}

.dataframe thead th {
    text-align: right;
}
</style>
|  | Band | Min | Max | Mean | Median | Std Dev | Count |
| 0 | Red (Band 1) | 0.000010 | 0.801670 | 0.111174 | 0.104933 | 0.038385 | 72930440 |
| 1 | Green (Band 2) | 0.000037 | 0.657114 | 0.103182 | 0.098467 | 0.032011 | 72931495 |
| 2 | Blue (Band 3) | 0.000153 | 0.551923 | 0.104978 | 0.099838 | 0.031800 | 72931862 |
| 3 | NIR (Band 4) | 0.000064 | 0.819185 | 0.197075 | 0.187860 | 0.060731 | 72931525 |
| 4 | RedEdge (Band 5) | 0.000005 | 0.724430 | 0.141161 | 0.134643 | 0.045160 | 72930929 |
| 5 | Band 6 (Band 6) | 255.000000 | 255.000000 | 255.000000 | 255.000000 | 0.000000 | 72931873 |

 
image.png (view on web)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>
MendeBadra left a comment (OpenDroneMap/ODM#1483)
Hello, there is the histogram values and some boxplots showing max and min: (I would say they're pretty normal looking histograms)

image.png (view on web)
<style scoped> .dataframe tbody tr th:only-of-type { vertical-align: middle; }.dataframe tbody tr th {
    vertical-align: top;
}

.dataframe thead th {
    text-align: right;
}
</style>
|  | Band | Min | Max | Mean | Median | Std Dev | Count |
| 0 | Red (Band 1) | 0.000010 | 0.801670 | 0.111174 | 0.104933 | 0.038385 | 72930440 |
| 1 | Green (Band 2) | 0.000037 | 0.657114 | 0.103182 | 0.098467 | 0.032011 | 72931495 |
| 2 | Blue (Band 3) | 0.000153 | 0.551923 | 0.104978 | 0.099838 | 0.031800 | 72931862 |
| 3 | NIR (Band 4) | 0.000064 | 0.819185 | 0.197075 | 0.187860 | 0.060731 | 72931525 |
| 4 | RedEdge (Band 5) | 0.000005 | 0.724430 | 0.141161 | 0.134643 | 0.045160 | 72930929 |
| 5 | Band 6 (Band 6) | 255.000000 | 255.000000 | 255.000000 | 255.000000 | 0.000000 | 72931873 |

 
image.png (view on web)

**Comment by MendeBadra** [comment]
> Thanks for the very interesting thread. I need some guidance about how to use the orthomosaic output to derive NDVI and other spectral indices. The output is float32 reflectance values, but since they are not in the 0-1 values range, how should I proceed? Does the orthomosaic need some normalization or any other further processing? It's my first time processing drone imagery and I am trying to figure out a suitable processing pipeline. Thanks again!

I think you should proceed as is. I think normalization is not required because reflectance values should reflect measurement values. As for orthos that I've shown above, I tried Agisoft metashape and got similar results. But in metashape you can manually select which image should be taken into by hand. I manually excluded overexposed image and got a little better result. But still, the image looks like waves of sea.

**Comment by MendeBadra** [comment]
I think DJI p4 's sun sensor values are very varied in my flight.
