### ISSUE TITLE
Windows installation in non-default path causes error

### ISSUE THREAD

**Issue by pierotofy** [OpenDroneMap/ODM#1569]
> installed at a non-default path (in my user dir) and tried to run run.bat but it failed because it couldn't find geos_c.dll at ./venv/Library/bin/geos_c.dll .  Copying it from the shapely site-packages to that location solved it though

**Comment by coumbsek** [comment]
Strange, what command/dataset did you use ? Here we constantly instal ODM inside the AppData folder (so inside user dir) and we have not yet encounter this error.

**Comment by pierotofy** [comment]
Just `run.bat` without a dataset. 

It's possible that this might have been related to something else (thus the "possible bug") label. Glad it's working in your case.

**Comment by coumbsek** [comment]
I will try to reproduce next week

**Comment by HeDo88TH** [comment]
My Windows user is called `IT 2` and I tried to install ODM in `C:\Users\IT 2\ODM`. It gave me this error on startup:

`Unable to create process using 'C:\Users\IT 2\ODM\\python38\python.exe -X utf8 "C:\Users\IT 2\ODM\\run.py" --help'`

When trying to run a reconstruction:

```
(venv) C:\Users\IT 2\ODM>run D:\datasets\brighton-2
Unable to create process using 'C:\Users\IT 2\ODM\\python38\python.exe -X utf8 "C:\Users\IT 2\ODM\\run.py" D:\datasets\brighton-2'
```

I think it's something with the building of the path.

When trying to install in `Program files` the installer lacks sufficient privileges:

![err-perm](https://user-images.githubusercontent.com/7868983/219723046-2448084b-8c72-40e0-ab3c-203eceede97f.png)

It's at least an inconvenient to close the nasty error message and then right click on the installer -> run as administrator. I think the setup should be able to re-launch itself if the destination folder needs elevated privileges

**Comment by seanrl** [comment]
Replication steps for this issue in 3.0.4:
- Install ODM using the latest Windows binary release (I installed to ~/Programs/ODM)
- Open a powershell or cmd prompt window
- Execute "~/Programs/ODM/run.bat"

Its worth noting that the ODM Console doesn't have this issue.  It only crops up if you use your own console to run the batch file.  In the error, it lands on this line as being the culprit ` _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))`

A quick fix for me is to copy 2 files *geos.dll* and *geos_c.dll* from .\venv\Lib\site-packages\shapely\DLLs to .\venv\Library\bin (which has to be created because it doesn't exist)

**Comment by coumbsek** [comment]
> Its worth noting that the ODM Console doesn't have this issue. It only crops up if you use your own console to run the batch file. In the error, it lands on this line as being the culprit ` _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))`
> 
> A quick fix for me is to copy 2 files _geos.dll_ and _geos_c.dll_ from .\venv\Lib\site-packages\shapely\DLLs to .\venv\Library\bin (which has to be created because it doesn't exist)

This is normal, the ODM Console loads at lot of environment variables and configuration via the `winrunt.bat`and `win32env.bat`, if you want to use your own console you should have a look at it.

**Comment by coumbsek** [comment]
> Just `run.bat` without a dataset.
> 
> It's possible that this might have been related to something else (thus the "possible bug") label. Glad it's working in your case.

Tried to reproduce it but everything seems fine. Even run a complete dataset with no issue while ODM is intall inside : `C:\Users\MyUser\Documents\ODM>`

**Comment by coumbsek** [comment]
> My Windows user is called `IT 2` and I tried to install ODM in `C:\Users\IT 2\ODM`. It gave me this error on startup:
> 
> `Unable to create process using 'C:\Users\IT 2\ODM\\python38\python.exe -X utf8 "C:\Users\IT 2\ODM\\run.py" --help'`
> 
> I think it's something with the building of the path.

I tried with a space in path because I though it could be it but it worked. Are you sure the user launching ODM Console has read/wright access to the folder ?

To test if the issue comes from the building of the path just replace in `winrun.bat` the line 6 with this one:
`python -X utf8 "%ODMBASE%run.py" %*`
i.e. removing the extra `\`
