### ISSUE TITLE
How Can I get an orthophoto if I don't have a geographic reference system

### ISSUE THREAD

**Issue by mrosen** [OpenDroneMap/ODM#245]
Suppose I have have a collection of overlapping drone images but no GPS ephemeris and no GCPs.  I think I can still get through the meshing and texturing steps (right?).  Is there some way I can get odm_orthophoto to produce a rectified image?  Seems like there should be some value of resolution which would allow this.

**Comment by smathermather** [comment]
There's no magic way here-- even if you could find an appropriate resolution, you have no way of knowing which is your z axis. Agisoft gets around this by letting you interactively choose a view and choose to create an orthophoto from that view, but that requires a graphical interface.

**Comment by dakotabenjamin** [comment]
You can create a GCP file by hand, if you have accurate coordinates of a few (at least 3) landmarks in the images. I've seen instances of GCPs where the z axis was set to 0 or maybe you could guess. Note that it probably won't be as accurate.

**Comment by mrosen** [comment]
Can I ask for a little clarification on this:  what do we mean by confusion about the z axis.  We get a properly textured point cloud.  We know where the xy plane is in that reference system.  If we orthographically project down onto that, is that not the orthorectified image we seek?

**Comment by dakotabenjamin** [comment]
Well, "we" (humans, not computers) know the where the xy plane is in the textured model because we realize that it should be a planar surface. The software, OTOH, has no idea where x, y, or z is without a geographic reference. The orthorectified image could be projected from the 3D surface from any angle. When you've got a geographic reference, then there's a (0,0,0) point somewhere that represents real space-- the points or pixels or whatever in the surface are able to be oriented relative to that reference, and then the images can be projected "down" onto that surface (because now it has knowledge of what down is).

**Comment by mrosen** [comment]
I'm not following Benjamin's explanation.  The point cloud already has a reference system.  Why can't we use that?  When we do a 3D rendering of the point cloud (say, in some application that does that, like CloudCompare), we can position the camera in coordinates from the cloud's reference system.  As we move the z value out to infinity (and keeping x and y in the middle of their domains), I think the resulting image becomes the orthorectified image we seek.  Right?  We can do that without a UI.  What am I missing?

**Comment by smathermather** [comment]
The point cloud has an arbitrary reference system. I could be rotated 180 degrees from normal on any or all axes, so in order to perform what you suggest, we still need to get the Z axis correct. It's true that this does not necessarily require a graphical interface, but I can't see any trivial solution. Dakota is out of town at the moment, but maybe when he gets back he can post some screen shots of the difference between an unreferenced mesh and a referenced one.

**Comment by liwenzhuo** [comment]
hi~ Could anyone please tell me how does ODM process tie points after matching, then feed them to bundler? To my knowledge, bundler need a initial 3D coordinates. The question is how to estimate the initial 3D coordinates for tie points.

**Comment by smathermather** [comment]
Related: https://github.com/OpenDroneMap/OpenDroneMap/pull/440

**Comment by dakotabenjamin** [comment]
With #440 you can now get an ortho, but no guarantees that it will be useful.

**Comment by pierotofy** [comment]
For a while ODM has been generating orthophotos even for non-georeferenced datasets. This can be closed. :clinking_glasses:

**Comment by smathermather** [comment]
Here's an orthophoto of my espresso making setup as deployed in Rwanda:
![image](https://user-images.githubusercontent.com/1174901/77109052-a557f680-69f9-11ea-96db-29f7b6f1bb98.png)

It makes a nice surface model too:
![image](https://user-images.githubusercontent.com/1174901/77109141-cc162d00-69f9-11ea-8871-bbd2b86dd020.png)

**Comment by pierotofy** [comment]
lol
