### ISSUE TITLE
Beyond Hahog features

### ISSUE THREAD

**Issue by hy9be** [OpenDroneMap/ODM#628]
I am new to odm. Not sure if this is a dummy question. I see odm uses HAHOG in feature detection. But OpenSfm actually supports AKAZE, SIFT, SURF as well. What is the reason behind to pick HAHOG?
In OpenSfm, these are configurable through config.yaml file. But i did not see that file in odm project.

Thanks!

**Comment by CarlosGrohmann** [comment]
+1 for adding the other feature detection methods. I'd love to test them all.

**Comment by dakotabenjamin** [comment]
Like I said in the the gitter chat, this can be accomplished by editing https://github.com/OpenDroneMap/OpenDroneMap/blob/master/scripts/opensfm.py#L65

There are a lot of unused features of OpenSfm; some are not useful to us. I am working on an update to opensfm right now and there will be more config settings opened up when that happens. For now, I will not add different detection methods because that will take a lot of testing, but I will look favorably on pull requests to do so.

**Comment by hy9be** [comment]
Thanks!

**Comment by hy9be** [comment]
@dakotabenjamin Hey I am working on a PR to expose some other configs in opensfm. Would you mind sharing me the irrelevant items in the config file: https://github.com/mapillary/OpenSfM/blob/master/config.yaml?

**Comment by dakotabenjamin** [comment]
I haven't looked at everything in the sample file, but I know for example SURF and SIFT are both patented so we don't add them to ODM. I don't know about AKAZE, geometric estimation, track creation or navigation graphs. Bundle adjustment is relevant, but I think more for advanced usage. I'm currently working on the GPS param exposure because it affects other parts of the pipeline.

**Comment by hy9be** [comment]
@dakotabenjamin AKAZE is included in OpenCV3, so I guess it is patent-free: http://docs.opencv.org/master/d5/d51/group__features2d__main.html. 

I exposed the AKAZE feature type and its parameters. I had to use the opensfm-0.1.0 rather than the one for odm, because it hangs during the feature extraction process. No sure if a different opensfm release will have compatible issues with odm code base though. I suppose not, but need some testing maybe.

The only thing I am not sure is that, for aerial images, does AKAZE really has the potential to work better than HAHOG. I tried it out yesterday on my case. It was faster, but visually I do not think it delivers a better result.

**Comment by hy9be** [comment]
Let me reopen the issue so that more people could see it and may contribute some ideas.

**Comment by dakotabenjamin** [comment]
Yes plan to merge opensfm 0.1.0 because that's where I'm working as well.

**Comment by dakotabenjamin** [comment]
Hey @hy9be I think that config.yaml file is not well updated, use this: 
https://github.com/mapillary/OpenSfM/blob/8097631c090679c8ed64b083c844b76ab357a0a6/opensfm/config.py

**Comment by hy9be** [comment]
I recently worked on a image recognition project using convolutional neural network. The feature extraction ability of CNN is really amazing. Not sure if it will be a good idea to try out using CNN feature instead of Hahog or SWIFT in ODM. What you guys think?

**Comment by smathermather** [comment]
@hy9be -- CNNs for feature extraction are an interesting space. Any more thoughts on this?

**Comment by smathermather** [comment]
This is implemented.

**Comment by sbonaime** [comment]
> This is implemented.

Are you taking about CNNs ? If yes, how can we try this feature ? 
Thanks
