### ISSUE TITLE
Output mangled or application crash when having duplicates in dataset

### ISSUE THREAD

**Issue by fredlllll** [OpenDroneMap/ODM#643]
reproduce issue:
get one of the demo datasets and duplicate ~30 images into the same folder.
process dataset

result:
either mangled output or even crash while processing

expected:
duplicated datapoints shouldnt add any information to output, much less mangle it

rudimentary solution: scan for identical files before processing and only use one of them

another problem with this: images that are taken from almost the same place. i have only had one in our dataset where the problem arose, but i guess that would cause similar problems to just duplicate files

**Comment by dakotabenjamin** [comment]
What kind of errors are you getting?

**Comment by fredlllll** [comment]
i didnt record it =/ we built an automated system around opendronemap to process datasets from drones, and when processing the aukerman with 30 duplicated images, it just returned an empty error (usually that should contain the whole odm output), so i cant tell. i will run it again locally tomorrow if i can (my pc isnt the fastest and work also uses some cpu)

**Comment by mcnis003** [comment]
I get the same thing. I backup my images on Google Drive. Sometimes this causes duplicate files to be created. I had to write some code to remove these before running ODM. I don't have a copy of the error text but I believe the crash was during calculating depth maps or merging depth maps. I can recreate it if needed.

**Comment by fredlllll** [comment]
@mcnis003 i would appreciate it, as my computing capabilities are rather limited =/

**Comment by mcnis003** [comment]
I did it R because that is what I am most familiar with:

`list=list.files(path="/path/to/files",pattern="*pattern_here*.jpg",recursive = TRUE,full.names = TRUE)
for (i in 1:length(list)){
  if (file.exists(list[i])) file.remove(list[i])
}`

It could also be implemented in Bash using grep and rm if you are on Linux or Mac. Basically:

1. create a list of files that are duplicates using some sort of pattern recognition, in my case the duplicates are file_name(1).jpg so I search for the "(1)".
2. delete those files

**Comment by fredlllll** [comment]
oh i thought you were talking about the error text

**Comment by pierotofy** [comment]
ODM is capable of handling duplicate images well in the latest version (just confirmed with a duplicate brighton dataset):

![image](https://user-images.githubusercontent.com/1951843/92957861-410d7100-f437-11ea-86a1-f3803f36f3bd.png)

:+1:
