### ISSUE TITLE
How to do only orthophotos in ODM?

### ISSUE THREAD

**Issue by TURET-Tesis** [OpenDroneMap/ODM#683]
I want to do an orthotography of a terrain to get its NDVI, but ODM generates the textures and map of points, I would like to know if there is any way to generate only the orthophoto, this to optimize the analysis and not take so long to generate the orthophoto.
I would also like to know if there is an equal tool in ODM that can compare 2 orthophotos and generate a single one to get the NDVI.

**Comment by smathermather** [comment]
Hi @Danicar7 -- the short answer is no. The process is a full photogrammetric toolchain, which requires the generation of intermediate 3D portions in order to correct for all factors. In the FOSS arena, I know of no software that can do what you propose, which would require feature matching to be combined with thin plate spline corrections between images.

I am very interested in this question as well, and long-term hope to build a tool that can do this, but for now, this is definitely not a function of ODM.

**Comment by fredlllll** [comment]
the orthophoto is generated from the georeferenced mesh. thats why it has to be generated beforehand.

**Comment by PeterSprague** [comment]
"I would also like to know if there is an equal tool in ODM that can compare 2 orthophotos and generate a single one to get the NDVI."

Not in ODM, but if orthophotos align to the resolution you need, use QGIS raster calculator.  Can also align your orthos to known georeference points.

**Comment by dakotabenjamin** [comment]
We've made some progress on this, using the `--fast-orthophoto`  option. Try it out and see how that works for you. 

In the meantime I'm going to close this. Feel free to head to our [forum](http://community.opendronemap.org) to continue the discussion.
