### ISSUE TITLE
Could opendronemap make use of LIDAR LAS files along with TIFFs to generate orthophotoes?

### ISSUE THREAD

**Issue by timuckun** [OpenDroneMap/ODM#805]
If a LAS file is available could I use that instead of generating DEMs from the Tiffs?

**Comment by pierotofy** [comment]
Hey @timuckun, we already use the LAS file to generate the DEM products.

**Comment by timuckun** [comment]
Is there any documentation on this? Where do I put the LAS files?  How does it match the LIDAR data to the JPGs?

**Comment by smathermather** [comment]
Hi @timuckun -- to clarify, the output from the photogrammetric point cloud is a las formatted filein the odm_georeferencing subdirectory. You could run the process up to the stage where you want to insert the lidar data, replace odm_georeferenced_model.las with your lidar las, and continue the processing.

Use ```--start-with``` and ```--end-with``` to control where your process begins and ends in order to do the insert. And let us know how it goes!

(For more on starting and ending, see: http://docs.opendronemap.org/using.html#additional-arguments)

**Comment by smathermather** [comment]
Also, here's the docs on dataset structure: http://docs.opendronemap.org/dataset.html
