### ISSUE TITLE
control spatial extent of reconstruction

### ISSUE THREAD

**Issue by petrasovaa** [OpenDroneMap/ODM#852]
In case of oblique images ODM tries to reconstruct area way beyond the region of interest. Providing a bounding box or a vector file would, I assume, make reconstruction or at least DSM creation and meshing faster.

**Comment by smathermather** [comment]
Ooh, good point. IDK how hard it would be to wrap in with SfM step, but pretty trivial I’d think for meshing.

**Comment by garlac** [comment]
I am looking for similar requirement. Due to taking images in circular path, I get sky visible in my images along with the area of focus.

This creates very huge point cloud with additional points around the area representing sky. Screen shot below - 
![processing_area](https://user-images.githubusercontent.com/40228026/49081449-e52b2580-f26c-11e8-8ade-318a9a02c666.png)

It would be helpful if the user is provided an option to limit the processing area before the processing begins  (OR),
an option like snipping tool to cut the focus area alone.

**Comment by garlac** [comment]
[http://community.opendronemap.org/t/limit-processing-area-or-bounding-box/1455/4](url)

**Comment by smathermather** [comment]
Hmm, still an interesting request. I will keep this open @petrasovaa

**Comment by kikislater** [comment]
Grass region computation concept in ODM ! Love the concept ^^

**Comment by smathermather** [comment]
:D

**Comment by pierotofy** [comment]
I think the photogrammetry way to do this would be to mask the sky regions (via 2D image masks); it's a more general approach that would work with both geo and non-georeferenced datasets.

The bounding box approach is potentially faster though (no need to mask every image, just choose an area).

**Comment by smathermather** [comment]
Masking implemented in 2.0: https://github.com/OpenDroneMap/ODM/pull/1156#issuecomment-692880000

Huge for 360 camera use too.

**Comment by pierotofy** [comment]
Done!
