### ISSUE TITLE
[Feature Request ] Faster Merging Merge step of Split Merge 

### ISSUE THREAD

**Issue by smathermather** [OpenDroneMap/ODM#988]
`gdalwarp` is used for the merge step in split-merge approaches. gdalwarp is quite a fast way to merge the data, unless blending is used, at which point it becomes painfully slow. It would be nice to either replace gdalwarp at this step with an optimized solution or optimize gdalwarp and contribute upstream.

**Comment by pierotofy** [comment]
I think part of the bottleneck is the code in https://github.com/OSGeo/gdal/blob/d5f6bb89b0e0db0a06489419050d432e8f58ff47/gdal/alg/gdalcutline.cpp#L70 so perhaps work could simply go toward optimizing that routine in GDAL.

**Comment by pierotofy** [comment]
Also, I think it's safe to say that lanczos interpolation is probably overkill, we should switch to bilinear or even near since most orthophotos will end up having the same resolution (we're just stitching them together with blending, we're not scaling/rotating them, for the most part). This alone should give a 2-3x speed up.

**Comment by smathermather** [comment]
Ya, lanczos is overkill for most non-quantitative applications. It still makes some sense for elevation models, as it keeps the features from moving too much.

**Comment by pierotofy** [comment]
`bilinear` interpolation is now used in #992

**Comment by smathermather** [comment]
+1

**Comment by pierotofy** [comment]
This has been done some time ago. :clinking_glasses:

**Comment by smathermather** [comment]
And boy is it much faster and less memory intensive. I've never seen PDAL work so hard.
